namespace BidUp.BusinessLogic.DTOs.CommonDTOs;

public enum ErrorCode
{
    AUTH_VIOLATE_REGISTER_RULES,
    AUTH_INVALID_USERNAME_OR_PASSWORD,
    AUTH_ACCOUNT_IS_LOCKED_OUT,
    AUTH_EMAIL_NOT_CONFIRMED,
    AUTH_INVALID_REFRESH_TOKEN,
    AUTH_PASSWORD_RESET_FAILD,
    AUTH_PASSWORD_CHANGE_FAILD,

    BID_NOT_ALLOWED,
    BID_AMOUNT_INVALID,
    AUCTION_ENDED,

    REVIEW_ALREADY_EXISTS,

    PERMISSION_DENIED,
    RESOURCE_NOT_FOUND,
    UPLOADED_FILE_INVALID,
    USER_INPUT_INVALID,
    SERVER_INTENRAL_ERROR
}